# Use an official Python runtime as a parent image
FROM python:3.11-slim-bookworm

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install uv (if not using pip directly)
RUN pip install uv

# Copy uv requirements files and install dependencies
# Assuming you have requirements.in and requirements.txt (generated by uv compile)
COPY requirements.txt .
RUN uv pip install -r requirements.txt --system --no-cache-dir

# Copy the Django project
COPY . /app/

# Collect static files
RUN python manage.py collectstatic --noinput

# Expose the port Gunicorn will run on
EXPOSE 8000

# Command to run the application using Gunicorn
# Adjust 'your_project_name.wsgi' to your actual project name
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "hub.wsgi:application"]