# Generated by Django 5.2.6 on 2026-01-29 14:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Account name (e.g., 'Fidelity 401k', 'Vanguard Roth IRA')", max_length=200)),
                ('account_type', models.CharField(choices=[('401K', '401(k)'), ('ROTH_401K', 'Roth 401(k)'), ('TRADITIONAL_IRA', 'Traditional IRA'), ('ROTH_IRA', 'Roth IRA'), ('BROKERAGE', 'Brokerage/Investment Account'), ('CASH', 'Cash/Savings Account'), ('HSA', 'Health Savings Account (HSA)'), ('OTHER', 'Other')], max_length=20)),
                ('institution', models.CharField(blank=True, help_text="Financial institution (e.g., 'Fidelity', 'Vanguard')", max_length=200)),
                ('is_taxable', models.BooleanField(default=False, help_text='Check if this is a taxable account (Brokerage, Cash). Uncheck for tax-advantaged accounts (401k, IRA, HSA).')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this account from portfolio view')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this account')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Date of this balance snapshot')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Account balance on this date', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this snapshot')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='financial.portfolioaccount')),
            ],
            options={
                'ordering': ['-snapshot_date', 'account__name'],
                'unique_together': {('account', 'snapshot_date')},
            },
        ),
    ]
