# Generated by Django 5.2.6 on 2026-01-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioaccount',
            name='tax_treatment',
            field=models.CharField(choices=[('PRE_TAX', 'Pre-Tax (Traditional 401k/IRA) - Contributions reduce taxable income, withdrawals taxed as ordinary income'), ('ROTH', 'Roth (Roth 401k/IRA) - Post-tax contributions, tax-free qualified withdrawals'), ('TAXABLE', 'Taxable Brokerage - Subject to capital gains tax'), ('HSA', 'HSA - Triple tax advantaged (pre-tax contributions, tax-free growth, tax-free medical withdrawals)'), ('CASH', 'Cash/Savings - Interest taxed as ordinary income')], default='PRE_TAX', help_text='Tax treatment of contributions and withdrawals', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioaccount',
            name='is_taxable',
            field=models.BooleanField(default=False, help_text='Automatically set based on tax treatment (read-only)'),
        ),
    ]
