# Generated by Django 5.2.6 on 2026-01-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_portfolioaccount_tax_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioaccount',
            name='tax_treatment',
            field=models.CharField(choices=[('PRE_TAX', 'Pre-Tax (Traditional 401k/IRA) - Contributions reduce taxable income, withdrawals taxed as ordinary income'), ('ROTH', 'Roth (Roth 401k/IRA) - Post-tax contributions, tax-free qualified withdrawals'), ('PENSION', 'Pension/Lump Sum - Retirement fund that can be taken as lump sum or annuity, taxed as ordinary income'), ('TAXABLE', 'Taxable Brokerage - Subject to capital gains tax'), ('HSA', 'HSA - Triple tax advantaged (pre-tax contributions, tax-free growth, tax-free medical withdrawals)'), ('CASH', 'Cash/Savings - Interest taxed as ordinary income')], default='PRE_TAX', help_text='Tax treatment of contributions and withdrawals', max_length=20),
        ),
    ]
