# Generated by Django 5.2.6 on 2026-02-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_portfolioaccount_tax_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='First day of the month for this record', unique=True)),
                ('kwh_consumed', models.DecimalField(blank=True, decimal_places=2, help_text='Electricity consumed from grid (kWh)', max_digits=10, null=True)),
                ('kwh_sent', models.DecimalField(blank=True, decimal_places=2, help_text='Electricity sent back to grid (kWh)', max_digits=10, null=True)),
                ('net_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Net electricity from grid (kWh)', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total bill cost ($)', max_digits=10, null=True)),
                ('cost_per_kwh', models.DecimalField(blank=True, decimal_places=6, help_text='Cost per kWh ($/kWh)', max_digits=10, null=True)),
                ('received_per_kwh', models.DecimalField(blank=True, decimal_places=6, help_text='Credit received per kWh sent ($/kWh)', max_digits=10, null=True)),
                ('produced_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Solar electricity produced (kWh)', max_digits=10, null=True)),
                ('kwh_combined', models.DecimalField(blank=True, decimal_places=2, help_text='Total electricity used (grid + solar)', max_digits=10, null=True)),
                ('percent_from_solar', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of usage from solar (%)', max_digits=5, null=True)),
                ('savings', models.DecimalField(blank=True, decimal_places=2, help_text='Savings from solar production ($)', max_digits=10, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, help_text='Credits from excess solar production ($)', max_digits=10, null=True)),
                ('savings_plus_credits', models.DecimalField(blank=True, decimal_places=2, help_text='Total savings + credits ($)', max_digits=10, null=True)),
                ('ev_mileage', models.DecimalField(blank=True, decimal_places=2, help_text='EV mileage driven (miles)', max_digits=10, null=True)),
                ('ev_miles_per_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='EV efficiency (miles/kWh)', max_digits=10, null=True)),
                ('ev_usage_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Electricity used by EV (kWh)', max_digits=10, null=True)),
                ('produced_minus_ev', models.DecimalField(blank=True, decimal_places=2, help_text='Solar production minus EV usage (kWh)', max_digits=10, null=True)),
                ('net_bill_minus_credits', models.DecimalField(blank=True, decimal_places=2, help_text='Net bill after credits ($)', max_digits=10, null=True)),
                ('comments', models.TextField(blank=True, help_text='Optional comments')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Electricity Usage',
                'verbose_name_plural': 'Electricity Usage',
                'ordering': ['-date'],
            },
        ),
    ]
