# Generated by Django 5.2.6 on 2026-02-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_electricityusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='First day of the month for this record', unique=True)),
                ('net_worth', models.DecimalField(decimal_places=2, help_text='Total net worth ($)', max_digits=15)),
                ('change_from_previous', models.DecimalField(blank=True, decimal_places=2, help_text='Dollar change from previous month ($)', max_digits=15, null=True)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=4, help_text='Percent change from previous month (as decimal, e.g., 1.05 = 5% increase)', max_digits=10, null=True)),
                ('comments', models.TextField(blank=True, help_text='Optional comments')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Net Worth',
                'verbose_name_plural': 'Net Worth',
                'ordering': ['-date'],
            },
        ),
    ]
