# Generated by Django 5.2.6 on 2026-05-25 21:17

import financial.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_networth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_spending', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text="Target monthly spending in today's dollars", max_digits=12)),
                ('spending_inflation_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0300'), help_text='Annual inflation rate applied to spending (e.g., 0.03)', max_digits=6)),
                ('ss_monthly_benefit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Expected Social Security monthly benefit in today's dollars", max_digits=10)),
                ('ss_inflation_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), help_text='Annual COLA adjustment for Social Security (e.g., 0.02)', max_digits=6)),
                ('ss_start_age', models.DecimalField(decimal_places=1, default=Decimal('67.0'), help_text='Age to start receiving Social Security', max_digits=4)),
                ('current_age', models.DecimalField(decimal_places=1, default=Decimal('50.0'), help_text='Your current age', max_digits=4)),
                ('max_age', models.IntegerField(default=95, help_text='Maximum age for forecast horizon')),
                ('withdrawal_order', models.JSONField(default=financial.models._default_withdrawal_order, help_text='Ordered list of account type codes for portfolio withdrawals')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forecast Settings',
            },
        ),
        migrations.AddField(
            model_name='portfolioaccount',
            name='annual_growth_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0700'), help_text='Expected annual growth rate for forecasting (e.g., 0.07 for 7%)', max_digits=6),
        ),
        migrations.AddField(
            model_name='portfolioaccount',
            name='pension_benefit_age',
            field=models.IntegerField(blank=True, help_text='Age when pension benefits begin (pension accounts only)', null=True),
        ),
        migrations.AddField(
            model_name='portfolioaccount',
            name='pension_monthly_benefit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Monthly pension benefit in today's dollars (pension accounts only)", max_digits=12, null=True),
        ),
    ]
