# Generated by Django 5.2.6 on 2026-05-25 23:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_forecast_and_account_growth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastsettings',
            name='current_age',
        ),
        migrations.AddField(
            model_name='forecastsettings',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Your date of birth — current age is calculated dynamically', null=True),
        ),
        migrations.AddField(
            model_name='forecastsettings',
            name='effective_tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2200'), help_text='Estimated effective tax rate on taxable withdrawals and income (e.g., 0.22 for 22%)', max_digits=5),
        ),
    ]
