# Generated by Django 5.2.6 on 2026-05-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_roth_conversions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(db_index=True, help_text='Heating season, e.g. 2024-2025', max_length=9)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('fuel_type', models.CharField(choices=[('corn', 'Corn'), ('pellets', 'Pellets'), ('propane', 'Propane')], max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='lbs (corn), bags (pellets), gallons (propane)', max_digits=10, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=6, help_text='$/lb, $/bag, or $/gallon', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heating Record',
                'verbose_name_plural': 'Heating Records',
                'ordering': ['season', 'month'],
                'unique_together': {('season', 'month', 'fuel_type')},
            },
        ),
    ]
