apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homelab-hub-postgres-backup-pvc
  namespace: homelab-hub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
