apiVersion: batch/v1
kind: CronJob
metadata:
  name: homelab-hub-ping-hosts
  namespace: homelab-hub
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ping-hosts
              image: jaysuzi5/homelab-hub:latest
              imagePullPolicy: Always
              command: ["python", "manage.py", "ping_hosts"]
              envFrom:
                - configMapRef:
                    name: homelab-config
                - secretRef:
                    name: homelab-hub-secrets
