# Generated by Django 5.2.6 on 2026-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcall',
            name='source',
            field=models.CharField(db_index=True, default='homelab-hub', max_length=64),
        ),
        migrations.AddField(
            model_name='agentcall',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='agentcall',
            constraint=models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_agentcall_source_sourceid'),
        ),
    ]
