# Generated by Django 5.2.6 on 2026-04-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeSession',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('project_path', models.CharField(max_length=512)),
                ('project_name', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_min', models.FloatField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('message_count', models.IntegerField(default=0)),
                ('tool_call_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaudeWeeklyPeak',
            fields=[
                ('recorded_at', models.DateField(primary_key=True, serialize=False)),
                ('message_count', models.IntegerField()),
                ('tool_call_count', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaudeDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model', models.CharField(max_length=64)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('api_equiv_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('message_count', models.IntegerField(default=0)),
                ('tool_call_count', models.IntegerField(default=0)),
                ('session_count', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'model'],
                'unique_together': {('date', 'model')},
            },
        ),
    ]
