# Generated by Django 5.2.6 on 2026-04-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('session_pct', models.FloatField(blank=True, null=True)),
                ('session_resets_at', models.DateTimeField(blank=True, null=True)),
                ('weekly_pct', models.FloatField(blank=True, null=True)),
                ('weekly_resets_at', models.DateTimeField(blank=True, null=True)),
                ('extra_usage_enabled', models.BooleanField(default=False)),
                ('extra_usage_credits_used', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'get_latest_by': 'fetched_at',
            },
        ),
    ]
