# Generated by Django 5.2.6 on 2026-04-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claude_usage', '0002_claudeusagesnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claudedailyusage',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='claudesession',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='claudeweeklypeak',
            name='message_count',
        ),
    ]
