# Generated by Django 5.2.6 on 2026-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubconfig',
            name='value',
            field=models.TextField(),
        ),
    ]
