# Generated by Django 5.2.6 on 2026-03-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateField(help_text='Date the book was finished')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('open_library_key', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_read'],
            },
        ),
    ]
