# Generated by Django 5.2.6 on 2026-04-23 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_book_cover_local'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(help_text='Time of day (allows multiple entries per day)')),
                ('category', models.CharField(choices=[('yousician', 'Yousician'), ('youtube', 'YouTube'), ('free_play', 'Free Play'), ('other', 'Other')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('skill_lead', models.BooleanField(default=False)),
                ('skill_chords', models.BooleanField(default=False)),
                ('skill_finger_picking', models.BooleanField(default=False)),
                ('skill_strumming', models.BooleanField(default=False)),
                ('skill_scales', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guitar_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
