# Generated by Django 5.2.6 on 2026-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredhost',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Not always on (e.g. desktop that sleeps) — excluded from System Status card issues'),
        ),
    ]
