# Generated by Django 5.2.6 on 2026-03-22 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(help_text='Time of day (to allow multiple entries per day)')),
                ('activity', models.CharField(choices=[('walk', 'Walk'), ('walk_run', 'Walk/Run'), ('run', 'Run'), ('bike', 'Bike'), ('swim', 'Swim')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance_miles', models.DecimalField(decimal_places=1, help_text='Distance in miles', max_digits=6)),
                ('distance_yards', models.PositiveIntegerField(blank=True, help_text='Raw yards entered (swim only)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
