# Generated by Django 5.2.6 on 2026-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_stepprefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepentry',
            name='bike_miles',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Miles biked that day', max_digits=5),
        ),
        migrations.AddField(
            model_name='stepprefs',
            name='steps_per_bike_mile',
            field=models.PositiveIntegerField(default=1400, help_text='Steps credited for one mile biked'),
        ),
    ]
