# Generated by Django 5.2.6 on 2026-08-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_stepentry_bike_miles_stepprefs_steps_per_bike_mile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StepPrefs',
        ),
    ]
