# Generated by Django 5.2.6 on 2026-08-09 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_seed_step_conversion_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightgoal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weightgoal',
            name='tier',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='weightgoal',
            unique_together={('user', 'target_date', 'tier')},
        ),
    ]
