from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard.views import (
    home, k8s, energy, networking,
    todo_tasks, todo_task_complete,
    otel_overview, otel_endpoint_detail, otel_transaction_detail,
    otel_logging_overview, otel_logging_transactions,
    otel_trace_overview, otel_trace_detail_view,
    otel_metrics_overview, otel_metrics_query_view,
    card_k8s, card_synology, card_claude, card_network,
    card_emporia_chart, card_emporia_daily, card_splunk, card_weather,
    card_aws_billing, card_aws_billing_refresh, card_backup, card_status,
    status_chat,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("k8s", k8s, name="k8s"),
    path("energy/", energy, name="energy"),
    path("networking/", networking, name="networking"),
    path("accounts/", include("allauth.urls")),
    path('financial/', include('financial.urls')),
    path('hobbies/', include('hobbies.urls')),
    path('health/', include('health.urls')),
    path('claude-usage/', include('claude_usage.urls')),
    path('otel/', otel_overview, name='otel_overview'),
    path('otel/logging/', otel_logging_overview, name='otel_logging_overview'),
    path('otel/logging/transactions/', otel_logging_transactions, name='otel_logging_transactions'),
    path('otel/trace/', otel_trace_overview, name='otel_trace_overview'),
    path('otel/trace/detail/', otel_trace_detail_view, name='otel_trace_detail'),
    path('otel/metrics/', otel_metrics_overview, name='otel_metrics_overview'),
    path('otel/metrics/query/', otel_metrics_query_view, name='otel_metrics_query'),
    path('otel/endpoint-detail/', otel_endpoint_detail, name='otel_endpoint_detail'),
    path('otel/transaction-detail/', otel_transaction_detail, name='otel_transaction_detail'),
    path('todo/tasks/', todo_tasks, name='todo_tasks'),
    path('todo/tasks/<int:task_id>/complete/', todo_task_complete, name='todo_task_complete'),
    path('dashboard/api/card/k8s/', card_k8s, name='card_k8s'),
    path('dashboard/api/card/synology/', card_synology, name='card_synology'),
    path('dashboard/api/card/claude/', card_claude, name='card_claude'),
    path('dashboard/api/card/network/', card_network, name='card_network'),
    path('dashboard/api/card/emporia-chart/', card_emporia_chart, name='card_emporia_chart'),
    path('dashboard/api/card/emporia-daily/', card_emporia_daily, name='card_emporia_daily'),
    path('dashboard/api/card/splunk/', card_splunk, name='card_splunk'),
    path('dashboard/api/card/weather/', card_weather, name='card_weather'),
    path('dashboard/api/card/aws-billing/', card_aws_billing, name='card_aws_billing'),
    path('dashboard/api/card/aws-billing/refresh/', card_aws_billing_refresh, name='card_aws_billing_refresh'),
    path('dashboard/api/card/backup/', card_backup, name='card_backup'),
    path('dashboard/api/card/status/', card_status, name='card_status'),
    path('dashboard/api/status/chat/', status_chat, name='status_chat'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
